version: '3.9'

services:

  backend:
    build: ./backend
    container_name: backend
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
    volumes:
      - ./backend:/usr/backend
    ports:
      - 3001:3001


  db:
    image:  mysql:8.0.21
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    cap_add:
      - SYS_NICE
   
